name: Python-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - nodejs
  - pip:
    - traittypes
    - traitlets
    - ipywidgets>=7.4
    - Pillow
    - scikit-image>=0.13
    - requests
    - ipywebrtc>=0.4
    - pythreejs>=1.0
    - jupyterlab>=0.34
    - notebook>=5.3
  - ipyvolume
